In [2]:
import numpy as np
mat = np.arange(12).reshape(3,4)
mat[1,2]


6

In [19]:
import numpy as np
a = np.arange(5)
a = np.array([32, 34, 36, 38, 40, 42])

In [22]:
from numpy import pi
arr = np.linspace(0,4,33)
arr[9]


1.125

In [47]:
import numpy as np
arr = np.arange(5,15,1)
np.exp(arr)

array([1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06])

In [36]:
import numpy as np
a = np.arange(13,25).reshape(2,6)
a.sum(axis = 0)

array([32, 34, 36, 38, 40, 42])

In [41]:
import numpy as np
np.arange(10,36,6)

array([10, 16, 22, 28, 34])